### ISSUE TITLE
no indication for downvoted comments

### ISSUE THREAD

**Issue by o2dazone** [dangwu/Octal#49]
I'm unsure if the API surfaces this data, but Hacker News has variants of grey that dim a comment based on how popular they are. Octal does not seem to do this.

[here is an example thread](https://news.ycombinator.com/item?id=17731487)

[More on this undocumented feature](https://github.com/minimaxir/hacker-news-undocumented#downvoting-comments)

Looking into the CSS of the HN website, it seems to have multiple variants

```css
.c00, .c00 a:link { color:#000000; }
.c5a, .c5a a:link, .c5a a:visited { color:#5a5a5a; }
.c73, .c73 a:link, .c73 a:visited { color:#737373; }
.c82, .c82 a:link, .c82 a:visited { color:#828282; }
.c88, .c88 a:link, .c88 a:visited { color:#888888; }
.c9c, .c9c a:link, .c9c a:visited { color:#9c9c9c; }
.cae, .cae a:link, .cae a:visited { color:#aeaeae; }
.cbe, .cbe a:link, .cbe a:visited { color:#bebebe; }
.cce, .cce a:link, .cce a:visited { color:#cecece; }
.cdd, .cdd a:link, .cdd a:visited { color:#dddddd; }
```

Here are a few screenshots of the website vs Octal

![IMG_0556](https://user-images.githubusercontent.com/1907517/54285093-85783200-455e-11e9-8721-57820575dac7.jpg)

![IMG_0557](https://user-images.githubusercontent.com/1907517/54285106-8dd06d00-455e-11e9-9f83-44177bb22016.jpg)
